const data = [
  {
    id: "01",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "solar",
    name: "solar",
    qty: 8,
    price: 210,
  },
  {
    id: "02",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "drone",
    name: "drone",
    qty: 10,
    price: 150,
  },
  {
    id: "03",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "energy",
    name: "energy",
    qty: 12,
    price: 350,
  },
  {
    id: "04",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "solar",
    name: "solar",
    qty: 13,
    price: 65,
  },
  {
    id: "05",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "drone",
    name: "drone",
    qty: 5,
    price: 82,
  },
  {
    id: "06",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "solar",
    name: "solar",
    qty: 7,
    price: 82,
  },
  {
    id: "07",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "energy",
    name: "energy",
    qty: 9,
    price: 40,
  },
  {
    id: "08",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "drone",
    name: "drone",
    qty: 4,
    price: 240,
  },
  {
    id: "09",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "wind",
    name: "wind",
    qty: 3,
    price: 20,
  },
  {
    id: "10",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "solar",
    name: "solar",
    qty: 5,
    price: 10,
  },
  {
    id: "11",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "drone",
    name: "drone",
    qty: 5,
    price: 100,
  },
  {
    id: "12",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "energy",
    name: "energy",
    qty: 5,
    price: 530,
  },
  {
    id: "13",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "soalr",
    name: "solar",
    qty: 5,
    price: 35,
  },
  {
    id: "14",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "plate",
    name: "plate",
    qty: 5,
    price: 55,
  },
  {
    id: "15",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "turbine",
    name: "turbine",
    qty: 5,
    price: 10,
  },
  {
    id: "16",
    img: "/aaron-burden-0fA3gVTGwjQ-unsplash-min.jpg",
    alt: "Stand",
    name: "Stand",
    qty: 5,
    price: 12,
  },
];

export default data;
